#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 1440
#define SCREEN_HEIGHT 1440
#define CENTER_X SCREEN_WIDTH / 2.0f 
#define CENTER_Y SCREEN_HEIGHT / 2.0f 
#define ZOOM_FACTOR 1.5f 
#define EULER 2.71828
#define ZERO_SCROLL 0.0f
#define PERCENT_100 100.0f
#define DELTA_PIXELS 1.0f
#define POINT_RADIUS 1
#define ZOOM_PERCENT_TEXT_X 100
#define ZOOM_PERCENT_TEXT_Y 100
#define FPS_TEXT_X 50
#define FPS_TEXT_Y 50
#define TEXT_FONT_SIZE 75
#define TEXT_COLOR GREEN
#define MAX_POINTS 2000

#endif
